#version 450
#include "../utils.comp"

layout(binding = 0) readonly buffer src_buffer {
    uint32_t raw[];
};

layout(binding = 1) writeonly buffer dst_buffer {
    uint32_t depth[1024 * 1024];
    uint8_t stencil[1024 * 1024];
};

void main() {
     uint32_t val = raw[GetAddress()];
     ivec2 coord = GetImageCoord();
     uint32_t dst_addr = coord.y * gl_WorkGroupSize.x * gl_NumWorkGroups.x + coord.x;
     depth[dst_addr] = val & 0x00FFFFFFu;
     stencil[dst_addr] = uint8_t(val >> 24);
}
